name: Snake

on:
  schedule:
    - cron: '0 */6 * * *'  # roda a cada 6 horas
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Generate Snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg?palette=github-dark

      - name: Publish to output branch
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git checkout --orphan output
          git reset --hard
          git add dist
          git commit -m "Update Snake SVG"
          git push -f origin output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
